#
# The very first Ansible playbook run, this one just installs the packages we
# know we'll need later.
#
---
- hosts: all
  become: true
  tasks:
  - name: Install base useful packages
    apt:
      name:
        - mariadb-client
        - mariadb-server
        - nginx
        - openjdk-21-jdk
        - tomcat10
        - libmariadb-java
      state: latest
