#
# This playbook sets up podman-compose to start the admin web UI
# automatically.
#
---
- hosts: all
  become: true
  tasks:
  - name: Make sure podman/compose is installed.
    ansible.builtin.apt:
      name: podman-compose
      update-cache: true
  - name: Make sure the compose directory is created.
    ansible.builtin.file:
      path: /etc/podman/compose
      mode: 0755
      state: directory
  - name: Make sure the compose/web directory is created.
    ansible.builtin.file:
      path: /etc/podman/compose/web
      mode: 0755
      state: directory
  - name: Copy in the podman-compose.yml file.
    ansible.builtin.template:
      src: podman-compose.yml.in
      dest: /etc/podman/compose/web/podman-compose.yml
  - name: Copy in the podman-compose config for systemd so we can start the service.
    ansible.builtin.copy:
      src: podman-compose@.service
      dest: /lib/systemd/system/podman-compose@.service
  - name: Enable the admin web UI.
    ansible.builtin.systemd:
      daemon-reload: true
      name: podman-compose@web.service
      enabled: true
      masked: false
      state: restarted
