# This file is the docker-compose configuration for the admin web UI.

version: "3.3"
services:
  printer:
    image: "riverbots42/zebra"
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - /dev:/dev
    privileged: true
  web:
    image: "riverbots42/love"
    ports:
      - "80:8080"
