#
# The very first Ansible playbook run, this one just installs the packages we
# know we'll need later.
#
---
- hosts: all
  become: true
  tasks:
  - name: Install base useful packages
    apt:
      name:
        - build-essential
        - ddclient
        - dkms
        - dnsmasq
        - docker
        - docker-compose
        - git
        - hostapd
        - iw
        - less
        - nmap
        - python3-nftables
        - sudo
        - tcpdump
        - vim
        - wireguard
      state: latest
      update_cache: true
