---
- hosts: all
  become: true
  tasks:
  - name: Install base useful packages
    apt:
      name:
        - ddclient
        - dnsmasq
        - docker
        - docker-compose
        - hostapd
        - iw
        - less
        - nmap
        - sudo
        - tcpdump
        - vim
        - wireguard
      state: latest
