#
# The most-complex of the ansible playbooks, we set up all the interface names
# and configure the IP addresses here, along with setting up the wifi AP and
# configure the DHCP daemon to hand out IP addresses on our networks.
#
---
- name: Configure network interfaces with correct names and WAN MAC.
  hosts: all
  become: true
  tasks:
  - name: Copy over the network interface autoconfig script.
    ansible.builtin.copy:
      src: generate-udev-rules.py
      dest: /usr/local/bin/generate-udev-rules
      mode: 0755
  - name: Run the network interface autoconfig script.
    shell: /usr/local/bin/generate-udev-rules
    register: interface_map
  - name: Output lines.
    debug:
      var: interface_map.stdout_lines
  - name: Copy in the network address config file.
    ansible.builtin.template:
      src: interfaces.j2
      dest: /etc/network/interfaces
  - name: Copy in the AP config file.
    ansible.builtin.template:
      src: hostapd.conf.j2
      dest: /etc/hostapd/hostapd.conf
  - name: Enable the hostapd daemon.
    ansible.builtin.systemd:
      name: hostapd.service
      enabled: true
      masked: false
      state: restarted
    ignore_errors: true
  - name: Copy in the DHCP config file.
    ansible.builtin.template:
      src: dnsmasq.conf.j2
      dest: /etc/dnsmasq.d/dnsmasq.conf
  - name: Enable the DHCP daemon.
    ansible.builtin.systemd:
      name: dnsmasq.service
      enabled: true
      masked: false
      state: restarted
    ignore_errors: true
