#
# This playbook sets up the service that manages connections to the robot.
#
---
- hosts: all
  become: true
  tasks:
  - name: Create the Robot Communication Manager service.
    ansible.builtin.copy:
      src: robot-packet-mangler.py
      dest: /usr/sbin/robot-packet-mangler
      mode: 0755
  - name: Copy in the Robot Communicate Manager systemd unit.
    ansible.builtin.copy:
      src: robot-packet-mangler.service
      dest: /lib/systemd/system/robot-packet-mangler.service
  - name: Enable the Robot Communication Manager service.
    ansible.builtin.systemd:
      name: robot-packet-mangler.service
      enabled: true
      masked: false
      state: restarted
